# TEST PLAN SYNTAX 
#   - overrides ALWAYS take precedence over workflow level settings
#   - default: `condition: all` for skip and run blocks
#     for example: a label `skip-all` AND this is a PR == this job is skipped
#   - optionally can specify `condition: any` in which case if any of label, 
#     event, branch, or path matches skip/run will execute
#   - if run and skip both match, run ALWAYS takes precedence and the job/workflow will run

overrides:
  - id: skip-all
    skip:
      labels: [skip-all]
      event: [pull_request]
    reason: skip-all label is set

  - id: force-run
    run:
      labels: [force-run]
      event: [pull_request]
    reason: force-run label is set

  - id: protected-branch
    run:
      branch: [main, "release/**"]
    reason: pushes to a protected branch always run everything

# maps workflow calls and conditions for running jobs
workflows:
  ci:
    jobs:
      lint:
        calls: lint
      test:
        calls: test

  lint:
    jobs:
      lint:
        run:
          path: [src, workflows]

  test:
    jobs:
      test:
        run:
          condition: any
          paths: [src]
          labels: [deep-test]
        skip:
          labels: [no-test]
          event: 
            pull_request: [labelled]
